# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6706d6601e353e77932c0b77c2836f1588ab619a88034cb0bbeeab35d63841ada34796c8f81861f12ca2a438c84901014891c36f786811947b99f3223f55049

test:
  secret_key_base: 85841ab0ac3168a117d054b70920140d6c26dcdeb44f48a9c62adeb705a70408f7ce5cbf46e230b7e6ea58f7cca7357e9fe2d1611ac00a1647a9ce04dc0941c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
